CREATE TABLE `employees ` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(250) NOT NULL,
	`last_name` VARCHAR(250) NOT NULL,
	`email` VARCHAR(250) NOT NULL,
	`phone` VARCHAR(250) NOT NULL,
	PRIMARY KEY (`id`)
);